name: Build and test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Set ESLint config environment variable
        run: echo "ESLINT_USE_FLAT_CONFIG=false" >> $GITHUB_ENV

      - name: Lint code
        run: yarn lint .

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: your-docker-hub-username/webapp:latest
          push: false  # Don't push the image to Docker Hub yet
