name: Build and test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Set ESLint config environment variable
        run: echo "ESLINT_USE_FLAT_CONFIG=false" >> $GITHUB_ENV

      - name: Lint code
        run: yarn lint .

      - name: Start the application
        run: yarn start &  # Start de server op de achtergrond

      - name: Wait for server to be ready
        run: sleep 5  # Wacht even om zeker te zijn dat de server is gestart

      - name: Run tests
        run: yarn test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: julienc15/webapp:latest
          push: true
